# Generated by Django 4.2.6 on 2023-10-16 23:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0002_post_remove_editors_text_editors_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='editors',
            name='remark',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
