# Generated by Django 4.2.6 on 2023-10-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0004_editor1_delete_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor1',
            name='name2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='editor1',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
