# Generated by Django 4.2.6 on 2023-10-17 13:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0005_editor1_name2_alter_editor1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor1',
            name='name2',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
