# Generated by Django 4.2.6 on 2023-10-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0006_alter_editor1_name2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor1',
            old_name='name2',
            new_name='ckeditor',
        ),
    ]
