# Generated by Django 4.2.6 on 2023-10-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0007_rename_name2_editor1_ckeditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor1',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
