# Generated by Django 4.2.6 on 2023-10-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0009_editor1_embed_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor1',
            old_name='embed_video',
            new_name='video',
        ),
    ]
