# Generated by Django 4.2.6 on 2023-10-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0010_rename_embed_video_editor1_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor1',
            old_name='video',
            new_name='django_embed_video',
        ),
    ]
