# Generated by Django 4.2.6 on 2023-10-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0011_rename_video_editor1_django_embed_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor1',
            name='video',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
