# Generated by Django 4.2.7 on 2023-11-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ok2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
            ],
        ),
    ]
