# Generated by Django 4.2.7 on 2023-11-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWiki', '0002_ok2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ok',
        ),
        migrations.DeleteModel(
            name='ok2',
        ),
    ]
