# Generated by Django 4.2.7 on 2023-11-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWiki', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ok2',
        ),
    ]
